name: Build and Push Docker Image

on:
  push:
    branches: [ main ]  # Or change to your working branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image 23f2004669@ds.study.iitm.ac.in
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: DOCKER_SECRET/docker-file:23f2004669
